### ISSUE TITLE
Dokumentation inte tillräckligt specifik

### ISSUE THREAD

**Issue by worldsayshi** [alexanderpersson/vantetider#1]
Jag förstår inte hur man ska kombinera ihop till en enda giltig url. Detta verkar tex inte fungera:

http://www.vantetider.se/api/Ajax/GetWaitingAndCapacityByService/Examination

**Comment by alexanderpersson** [comment]
För att för en lista på alla möjliga undersökningar så använder du http://www.vantetider.se/api/Ajax/GetServicesByArea/2 där 2 står för undersökning, 3 för operation och 4 för besök.

I det JSON svar du får så får du en lista på vilka val du har. Första objektet ser ut {"id":113,"Parent_id":19,"Disabled":false,"Uppdaterad":"2014-06-18T14:02:48.17","Name":"Magsäck - kirurgi (gastroskopi på kirurgisk enhet)","Servicecode":"10502","Dtype":"PhysicalService"} där är det viktiga Servicecode som du sedan använder i nästa anrop: http://www.vantetider.se/api/Ajax/GetWaitingAndCapacityByService/10502 för att få reda på väntetider för den undersökningen.
